method to fetch raw content from mogile fs instead of storing in a file
Yuav/MogileFS-PHP-Model pull request #5
Opened 2016-10-07 19:21 UTC by rajata07

This method allows to fetch the raw content from mogile fs. The use case is when you want to fetch the content without storing it in a temp file and pass through further to another cloud. For example, fetching millions of images from Mogile FS and pushing them to AWS S3. In this case, it is very useful not to create temporary files (so that server does not run out of space) and instead fetch raw binary files and push to AWS S3. 

Note: The method sends an curl request similar to fetchFile and store the result in a variable by setting CURLOPT_RETURNTRANSFER.

2016-10-09 06:52 UTC, Yuav commented
Storing the full file into ram can cause excessive ram usage for large files (imagine 100GB+ file!). It's also not a very efficient way to do the transfer if the goal is to read file from MogileFS, then forward to S3.

I would rather recommend using a [php stream handler](http://php.net/manual/en/ref.stream.php). That way you can push data to S3 at the same time as you pull it from MogileFS. I think [php://temp](http://php.net/manual/en/wrappers.php.php) is particularly well suited for this case

You can see an example usage with curl here:

https://github.com/Yuav/bitcasawebdav/blob/master/src/BitcasaWebdav/Client.php#L362

2016-10-09 12:02 UTC, rajata07 commented
Thanks for your reply and explanation. You are right, But for example in my case the average file size is in KB's which i think might be the case for several others as well. In this case, It's fast for me to directly read the file in memory and push to S3. We can rename the method  to "fetchContentInMemory" or "fetchFileInMemory" and give clear indication in documentation as well to use the method only for smaller files? What you think?

BTW, do you have an example or reference to a good tutorial which explains about pushing and writing data simultaneously with streaming? Thanks again!

2016-10-09 17:58 UTC, jskarpe requested changes
I would suggest you add tests to verify expected behavior

2016-10-09 17:58 UTC, Yuav commented on src/MogileFS/File/Mapper.php
> +        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
Returning transfer in addition to writing to file handle? Seems you're putting two copies of the downloaded file in memory now before returning!

2016-10-09 17:58 UTC, Yuav commented on src/MogileFS/File/Mapper.php
> +        return stream_get_contents($bodyStream);
You should rather return the stream resource handle, not read the entire stream into memory and the return. Then you can use that file handle to send to S3 again using curl:

    curl_setopt($ch, CURLOPT_INFILE, $fh);

2016-10-09 21:24 UTC, rajata07 commented on src/MogileFS/File/Mapper.php
> +        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
Sorry, didn't realise that. I have changed the code.

2016-10-09 21:25 UTC, rajata07 commented on src/MogileFS/File/Mapper.php
> +        return stream_get_contents($bodyStream);
Okay. Thanks again. I tried returning the resource handler and using S3 Stream wrapper, i could send file you file_put_contents and it works.

2016-10-09 21:28 UTC, rajata07 commented
Thanks. Added the unit tests as well. Please have a look once you have time

2016-10-10 07:55 UTC, Yuav commented
Looks better :-)

Could you rebase and squash your commits into one please?

2016-10-10 07:55 UTC, jskarpe approved these changes

2016-10-10 10:57 UTC, rajata07 commented
Thank you 👍  It's done. Please have a look.

2016-10-10 10:58 UTC, merged